pipelines:
  default:
    - step:
        name: Nuget Restore
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        caches:
         - dotnetcore
        script:
          - echo "test"
          - cat /etc/docker/daemon.json
          - cd emri-api-core
          - dotnet restore
          - dotnet build