pipelines:
  default:
    - step:
        name: Sync repo
        script:
          - git remote -v
          - git remote add --mirror=fetch secondary https://git@github.com/mattydolan/syncme
          - git fetch origin
          - git push secondary --all