pipelines:
  default:
    - step:
        name: Nuget Restore
        image: microsoft/dotnet:2-sdk
        caches:
         - dotnetcore
        script:
          - echo "test"
          - dir
          - dotnet restore