pipelines:
  default:
    - step:
        name: Nuget Restore
        image: microsoft/dotnet:3-sdk
        caches:
         - dotnetcore
        script:
          - echo "test"
          - cd emri-api-core
          - dotnet restore