pipelines:
  default:
    - step:
        name: Nuget Restore
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        caches:
         - dotnetcore
        script:
          - nuget restore
          - echo "test"
          - cd emri-api-core
          - dotnet build